### PR TITLE
Add JSONP support

### PR DESCRIPTION
**Pull request by craig552uk**
When a URL is requested with the 'callback' argument in the query string set to a non empty string, the response is returned wrapped in a function of that name.
JSONP responses are always returned with 200 HTTP code and "application/javascript" content type.

### CODE REVIEW

**Comment by skozlovf** [comment]
Ok. I think I'll move JSONP support to separate decorator 'as_json_p'.
Can you change the commit message to use imperative style ("Add bla bla" instad of "Added bla bla")?
Thanks, Craig.

**Comment by craig552uk** [comment]
You can have a separate decorator if you wish (it is your project :smile:) but for my use-case it was better to add jsonp support to the existing decorator. This meant that I could use the `as_json` decorator on all my api endpoints, which leaves the client the choice of requesting a jsonp or json response by defining (or not) the `callback` param in the URL.

**Comment by skozlovf** [comment]
Yep, I understand, but what if I want JSON response with `callback` param? Anyway I'll try to come up with more flexible way.

**Comment by craig552uk** [comment]
Hmm... in that case... how about making the callback param configurable?

**Comment by skozlovf** [comment]
Yep.
Fix commit message plz and I'll merge.

**Comment by craig552uk** [comment]
Done.
Cheers.

**Comment by skozlovf** [comment]
It's not a commit message :) But too much bureaucracy.

**Pull request merged**
